dist: trusty
sudo: required
services:
  - docker
language: node_js
node_js:
  - "8"
os:
  - linux
env:
  matrix:
    - DEPLOY_ENVIRONMENT=production DEPLOY_BRANCH=master DOCKER_IMAGE=orihoch/socialmap-app-main-page
    - ""
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - if [ "${DEPLOY_ENVIRONMENT}" == "" ]; then sh -e /etc/init.d/xvfb start; fi
install:
  - if [ "${DEPLOY_ENVIRONMENT}" == "" ]; then npm install; fi
script:
  - if [ "${DEPLOY_ENVIRONMENT}" == "" ]; then npm run lint; fi
  - if [ "${DEPLOY_ENVIRONMENT}" == "" ]; then npm run test; fi
  - if [ "${DEPLOY_ENVIRONMENT}" == "" ]; then npm run e2e; fi
  - |
    if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_BRANCH}" == "${DEPLOY_BRANCH}" ] &&\
       [ "${DOCKER_USERNAME}" != "" ] && [ "${DOCKER_PASSWORD}" != "" ] &&\
       [ "${TRAVIS_PULL_REQUEST}" == "false" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&\
        ( docker pull "${DOCKER_IMAGE}:${DEPLOY_BRANCH}"; true ) &&\
        docker build --cache-from "${DOCKER_IMAGE}:${DEPLOY_BRANCH}" \
                     -t "${DOCKER_IMAGE}:${TRAVIS_COMMIT}" \
                     -t "${DOCKER_IMAGE}:${DEPLOY_BRANCH}" \
                     . &&\
        docker push "${DOCKER_IMAGE}:${TRAVIS_COMMIT}" &&\
        docker push "${DOCKER_IMAGE}:${DEPLOY_BRANCH}"
    fi
